# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeProject

pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Messaging', '~> 5.15.0'

  target 'NativeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
    
    pod 'CodePush', :path => '../node_modules/react-native-code-push'

    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

    pod 'RNColorMatrixImageFilters', :path => '../node_modules/react-native-color-matrix-image-filters'
    
    pod 'React', :path => '../node_modules/react-native'
  end

  target 'NativeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

